[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Mengsen-W <mengsen_wang@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
managing_growing_projects = {path = "../managing_growing_projects/"}
