[package]
name = "plugin_demo"
version = "0.1.0"
authors = ["Mengsen <mengsen_wang@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
plugin = true
