[package]
name = "deriver_new"
version = "0.1.0"
authors = ["Mengsen <mengsen_wang@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"

[lib]
proc-macro = true
